--- #YAML:1.0
name:               Weaving-Tablet
version:            0.009.004
abstract:           Perl extension for manipulating tablet weaving patterns
author:
    - Michael Houghton <herveus@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:         0
    Moose:                0
    namespace::autoclean:  0
    Test::More:           0
    Tk:                   0
    Tk::ColorEditor:      0
    Tk::FileSelect:       0
    Tk::FontDialog:       0
    Tk::HList:            0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
